menu_heading:
  default: 'Custom Menu'
  description:
    en: "Change the wdiget heading"
menu_items:
  default: >-
    [{"text":"ğŸ§‘â€ğŸ¤â€ğŸ§‘ See all Members","url":"/u"},
    {"text":"âœ… Read the Guidelines","url":"/guidelines"},
    {"text":"ğŸ¨ Edit your Profile","url":"/my/preferences/profile"}]
  json_schema: '{ "type": "array", "format": "table", "uniqueItems": true, "items": { "type": "object", "properties": { "text": { "type": "string", "minLength": 1 }, "url": { "type": "string" } }, "additionalProperties": false } }'